/**
 * @module tests/e2e/doctor_lock_drift_test
 *
 * E2E: `markspec doctor` surfaces offline lockfile edge-drift as a
 * non-blocking warning (issue #658) — the proactive onramp for the
 * hard `MSL-L212` error `check` emits on the same drift. Uses a real
 * lockfile generated by `markspec lock`, then mutates the graph, so
 * the edge hash is genuine rather than hand-written.
 */

import { assertEquals, assertStringIncludes } from "@std/assert";
import { markspec, markspecInDir, markspecPersist } from "./helpers.ts";
import { BASE_FILES, CLEAN_REQ } from "./check_project_test.ts";

/** A system requirement satisfying REQ-0001 — one trace edge. */
const SREQ = `# System Requirements

- [SREQ-0001] Derived response time

  The system shall forward responses within 100 ms.

      Id: 01SREQ00000000000000000001
      Type: system-requirement
      Satisfies: REQ-0001
`;

Deno.test("doctor: in-sync lockfile reports no drift, exits 0", async () => {
  const run = await markspecPersist(["lock"], {
    files: { ...BASE_FILES, "docs/req.md": CLEAN_REQ, "docs/sreq.md": SREQ },
    permissions: ["--allow-net", "--allow-env", "--allow-run"],
  });
  try {
    assertEquals(run.code, 0, `lock failed: ${run.stderr}`);

    const { code, stderr } = await markspecInDir(run.dir, ["doctor"]);
    assertEquals(code, 0, stderr);
    assertEquals(stderr.includes("drifted"), false, stderr);

    const json = await markspecInDir(run.dir, ["doctor", "--format", "json"]);
    const data = JSON.parse(json.stdout);
    assertEquals(data.lockfile.present, true);
    assertEquals(data.lockfile.edgeDrift, false);
    assertEquals(
      data.diagnostics.some((d: { code: string }) =>
        d.code === "lockfile-edge-drift"
      ),
      false,
    );
  } finally {
    await Deno.remove(run.dir, { recursive: true });
  }
});

Deno.test("doctor: edge drift after lock warns and exits 2", async () => {
  const run = await markspecPersist(["lock"], {
    files: { ...BASE_FILES, "docs/req.md": CLEAN_REQ, "docs/sreq.md": SREQ },
    permissions: ["--allow-net", "--allow-env", "--allow-run"],
  });
  try {
    assertEquals(run.code, 0, `lock failed: ${run.stderr}`);

    // Drop the trace edge without re-locking → graph drifts from the pin.
    const sreqPath = `${run.dir}/docs/sreq.md`;
    const content = await Deno.readTextFile(sreqPath);
    await Deno.writeTextFile(
      sreqPath,
      content.replace("      Satisfies: REQ-0001\n", ""),
    );

    const { code, stderr } = await markspecInDir(run.dir, ["doctor"]);
    assertEquals(code, 2, stderr);
    assertStringIncludes(stderr, "drifted");
    assertStringIncludes(stderr, "markspec lock");

    const json = await markspecInDir(run.dir, ["doctor", "--format", "json"]);
    assertEquals(json.code, 2);
    const data = JSON.parse(json.stdout);
    assertEquals(data.lockfile.present, true);
    assertEquals(data.lockfile.edgeDrift, true);
    assertEquals(
      data.diagnostics.some((d: { code: string }) =>
        d.code === "lockfile-edge-drift"
      ),
      true,
      json.stdout,
    );
  } finally {
    await Deno.remove(run.dir, { recursive: true });
  }
});

Deno.test("doctor: no lockfile → no drift check, present:false, exits 0", async () => {
  const { code, stdout } = await markspec(["doctor", "--format", "json"], {
    files: { ...BASE_FILES, "docs/req.md": CLEAN_REQ },
  });
  assertEquals(code, 0, stdout);
  const data = JSON.parse(stdout);
  assertEquals(data.lockfile.present, false);
});

Deno.test("doctor: present-but-malformed lockfile → present:true, no drift fields, exits 0", async () => {
  const { code, stdout, stderr } = await markspec(
    ["doctor", "--format", "json"],
    {
      files: {
        ...BASE_FILES,
        "docs/req.md": CLEAN_REQ,
        "markspec.lock": "this is not valid toml {{{",
      },
    },
  );
  // Lockfile validity is `check`/`lock`'s concern, not doctor's — a malformed
  // lockfile is reported present but the drift comparison is skipped, so JSON
  // consumers never read `edgeDrift: false` as "in sync" when nothing ran.
  assertEquals(code, 0, stderr);
  const data = JSON.parse(stdout);
  assertEquals(data.lockfile.present, true);
  assertEquals("edgeDrift" in data.lockfile, false);
});
