/**
 * @module core/lock/serializer
 *
 * Deterministic TOML emitter for the Lockfile model. Tables and keys in
 * fixed order; arrays sorted by primary key; identical input → byte-
 * identical output. We hand-roll the emitter rather than using
 * @std/toml/stringify because we need (a) generated-file header
 * comment, (b) precise control over nested array-of-tables emission
 * order, (c) guaranteed key sort.
 */

import type {
  LockEdge,
  Lockfile,
  UpstreamProfile,
  UpstreamReference,
  UpstreamRegistry,
} from "./model.ts";

const HEADER =
  "#:schema https://driftsys.github.io/markspec/schemas/lock/v1.json\n" +
  "# @generated by `markspec lock` — do not hand-edit. Run `markspec lock`.\n" +
  "# See https://markspec.dev/lock for the format.\n";

/** Emit a deterministic TOML representation of a Lockfile. */
export function serializeLockfile(lf: Lockfile): string {
  const parts: string[] = [HEADER];
  parts.push(`schema = ${lf.schema}\n\n`);

  parts.push("[meta]\n");
  parts.push(`markspec-schema = ${lf.meta.markspecSchema}\n`);
  parts.push(`locked-at = ${tomlString(lf.meta.lockedAt)}\n`);
  if (lf.meta.toolchain !== undefined) {
    parts.push("\n[meta.toolchain]\n");
    parts.push(`min-version = ${tomlString(lf.meta.toolchain.minVersion)}\n`);
  }

  const refs = lf.upstreams
    .filter((u): u is UpstreamReference => u.kind === "reference")
    .slice()
    .sort((a, b) => a.slug.localeCompare(b.slug));
  for (const r of refs) {
    parts.push("\n[[upstream.reference]]\n");
    parts.push(`slug     = ${tomlString(r.slug)}\n`);
    parts.push(`id       = ${tomlString(r.id)}\n`);
    if (r.resolved !== undefined) {
      parts.push(`resolved = ${tomlString(r.resolved)}\n`);
    }
    if (r.hash !== undefined) parts.push(`hash     = ${tomlString(r.hash)}\n`);
    if (r.source !== undefined) {
      parts.push(`source   = ${tomlString(r.source)}\n`);
    }
    if (r.componentScheme !== undefined) {
      parts.push(`component-scheme = ${tomlString(r.componentScheme)}\n`);
    }
  }

  const profs = lf.upstreams
    .filter((u): u is UpstreamProfile => u.kind === "profile")
    .slice()
    .sort((a, b) => a.id.localeCompare(b.id));
  for (const p of profs) {
    parts.push("\n[[upstream.profile]]\n");
    parts.push(`id        = ${tomlString(p.id)}\n`);
    parts.push(`specifier = ${tomlString(p.specifier)}\n`);
    parts.push(`resolved  = ${tomlString(p.resolved)}\n`);
    parts.push(`hash      = ${tomlString(p.hash)}\n`);
    if (p.extends !== undefined) {
      parts.push(`extends   = ${tomlString(p.extends)}\n`);
    }
  }

  const regs = lf.upstreams
    .filter((u): u is UpstreamRegistry => u.kind === "registry")
    .slice()
    .sort((a, b) => a.id.localeCompare(b.id));
  for (const r of regs) {
    parts.push("\n[[upstream.registry]]\n");
    parts.push(`id                     = ${tomlString(r.id)}\n`);
    parts.push(`api                    = ${tomlString(r.api)}\n`);
    parts.push(
      `resolved-manifest-hash = ${tomlString(r.resolvedManifestHash)}\n`,
    );
    parts.push(`markspec-schema        = ${r.markspecSchema}\n`);
  }

  const bounds = lf.boundEntries.slice().sort((a, b) =>
    a.displayId.localeCompare(b.displayId)
  );
  for (const be of bounds) {
    parts.push("\n[[bound-entry]]\n");
    parts.push(`display-id = ${tomlString(be.displayId)}\n`);
    parts.push(`ulid       = ${tomlString(be.ulid)}\n`);
    const bindings = be.bindings.slice().sort((a, b) =>
      a.system.localeCompare(b.system)
    );
    for (const b of bindings) {
      parts.push("\n[[bound-entry.binding]]\n");
      parts.push(`external-id = ${tomlString(b.externalId)}\n`);
      parts.push(`system      = ${tomlString(b.system)}\n`);
      parts.push(`direction   = ${tomlString(b.direction)}\n`);
      if (b.lockedAttributes.size > 0) {
        parts.push("\n[bound-entry.binding.locked-attributes]\n");
        const sortedAttrs = [...b.lockedAttributes.entries()]
          .sort(([k1], [k2]) => k1.localeCompare(k2));
        for (const [k, v] of sortedAttrs) {
          parts.push(`${k} = ${tomlString(v)}\n`);
        }
      }
    }
  }

  const edges = lf.edges.slice().sort(compareLockEdges);
  for (const e of edges) {
    parts.push("\n[[edge]]\n");
    parts.push(`source-ulid     = ${tomlString(e.sourceUlid)}\n`);
    parts.push(`relation        = ${tomlString(e.relation)}\n`);
    if (e.targetUlid !== undefined) {
      parts.push(`target-ulid     = ${tomlString(e.targetUlid)}\n`);
    }
    parts.push(`authored-target = ${tomlString(e.authoredTarget)}\n`);
  }

  parts.push("\n[generated-cache]\n");
  parts.push(`edges-hash = ${tomlString(lf.generatedCache.edgesHash)}\n`);
  parts.push(`edges-count = ${lf.generatedCache.edgesCount}\n`);

  return parts.join("");
}

/**
 * Deterministic edge order: (sourceUlid, relation, authoredTarget,
 * targetUlid). The first three keys can collide when one authored target
 * resolves to two different ULIDs (e.g. duplicate display IDs across files
 * whose first-wins tiebreak flips per machine); targetUlid breaks that tie
 * so the comparator is a total order and input order never affects output.
 * A missing targetUlid (dangling reference) sorts as the empty string,
 * before any real ULID.
 */
function compareLockEdges(a: LockEdge, b: LockEdge): number {
  const s = a.sourceUlid.localeCompare(b.sourceUlid);
  if (s !== 0) return s;
  const r = a.relation.localeCompare(b.relation);
  if (r !== 0) return r;
  const t = a.authoredTarget.localeCompare(b.authoredTarget);
  if (t !== 0) return t;
  return (a.targetUlid ?? "").localeCompare(b.targetUlid ?? "");
}

/**
 * Emit a TOML basic string. Backslash and double-quote escaped; the three
 * common whitespace control characters (`\n`, `\r`, `\t`) are escaped so
 * that opaque external-system inputs (e.g. an `externalId` containing a
 * newline) cannot produce invalid TOML.
 */
function tomlString(s: string): string {
  return `"${
    s
      .replace(/\\/g, "\\\\")
      .replace(/"/g, '\\"')
      .replace(/\n/g, "\\n")
      .replace(/\r/g, "\\r")
      .replace(/\t/g, "\\t")
  }"`;
}
