// packages/markspec/core/lock/serializer_test.ts
import { assertEquals, assertStringIncludes } from "@std/assert";
import { serializeLockfile } from "./serializer.ts";
import { parseLockfile } from "./parser.ts";
import type { Lockfile } from "./model.ts";

const EMPTY_LOCKFILE: Lockfile = {
  schema: 1,
  meta: { markspecSchema: 1, lockedAt: "2026-05-25T12:00:00Z" },
  upstreams: [],
  boundEntries: [],
  edges: [],
  generatedCache: { edgesHash: "sha256:e3b0c44", edgesCount: 0 },
};

Deno.test("serializeLockfile: empty lockfile produces deterministic TOML", () => {
  const toml = serializeLockfile(EMPTY_LOCKFILE);
  assertStringIncludes(toml, "# @generated by `markspec lock`");
  assertStringIncludes(toml, "schema = 1");
  assertStringIncludes(toml, "markspec-schema = 1");
  assertStringIncludes(toml, 'locked-at = "2026-05-25T12:00:00Z"');
  assertStringIncludes(toml, "[generated-cache]");
  assertStringIncludes(toml, 'edges-hash = "sha256:e3b0c44"');
  assertStringIncludes(toml, "edges-count = 0");
});

Deno.test("serializeLockfile: identical input produces byte-identical output", () => {
  const a = serializeLockfile(EMPTY_LOCKFILE);
  const b = serializeLockfile(EMPTY_LOCKFILE);
  assertEquals(a, b);
});

Deno.test("serializeLockfile: References sorted by slug", () => {
  const lf: Lockfile = {
    ...EMPTY_LOCKFILE,
    upstreams: [
      {
        kind: "reference",
        slug: "RFC-2119",
        id: "https://www.rfc-editor.org/rfc/rfc2119",
      },
      {
        kind: "reference",
        slug: "ISO-26262-6",
        id: "urn:iso:std:iso:26262:-6:ed-2",
      },
    ],
  };
  const toml = serializeLockfile(lf);
  const isoIdx = toml.indexOf("ISO-26262-6");
  const rfcIdx = toml.indexOf("RFC-2119");
  assertEquals(
    isoIdx < rfcIdx,
    true,
    "ISO must come before RFC alphabetically",
  );
});

Deno.test("serializeLockfile: bound-entry binding sub-table emission order", () => {
  const lf: Lockfile = {
    ...EMPTY_LOCKFILE,
    boundEntries: [{
      displayId: "REQ-107",
      ulid: "01HGW2Q8MNP3RSTVWXYZABCDEF",
      bindings: [
        {
          externalId: "jira:PROJ-1423",
          system: "jira",
          direction: "bidirectional",
          lockedAttributes: new Map([["Title", "sha256:abc"]]),
        },
        {
          externalId: "doors:/Project/Reqs/REQ-107",
          system: "doors",
          direction: "inbound",
          lockedAttributes: new Map([["Status", "sha256:def"]]),
        },
      ],
    }],
  };
  const toml = serializeLockfile(lf);
  // First binding (doors) must come fully (including its locked-attrs sub-table)
  // before the second binding (jira) — bindings are sorted by system name,
  // so doors < jira alphabetically.
  const doorsBindingIdx = toml.indexOf("doors:/Project");
  const doorsLockedIdx = toml.indexOf('Status = "sha256:def"');
  const jiraBindingIdx = toml.indexOf("jira:PROJ-1423");
  assertEquals(doorsBindingIdx < doorsLockedIdx, true);
  assertEquals(doorsLockedIdx < jiraBindingIdx, true);
});

Deno.test("serializeLockfile: TOML string escaping handles backslash, quote, and control chars", () => {
  const lf: Lockfile = {
    ...EMPTY_LOCKFILE,
    upstreams: [{
      kind: "reference",
      slug: "edge-case",
      // Backslash, double-quote, newline, carriage return, tab — all common
      // hazards in opaque external-system inputs.
      id: 'urn:test:back\\slash:quote"in:newline\nreturn\rtab\there',
    }],
  };
  const toml = serializeLockfile(lf);
  // Each metachar appears in its TOML-escaped form on the `id = "…"` line.
  assertStringIncludes(toml, "\\\\");
  assertStringIncludes(toml, '\\"');
  assertStringIncludes(toml, "\\n");
  assertStringIncludes(toml, "\\r");
  assertStringIncludes(toml, "\\t");
});

Deno.test("serializeLockfile: emits [meta.toolchain] after [meta]", () => {
  const lf: Lockfile = {
    schema: 1,
    meta: {
      markspecSchema: 1,
      lockedAt: "2026-05-27T12:00:00Z",
      toolchain: { minVersion: "0.6" },
    },
    upstreams: [],
    boundEntries: [],
    edges: [],
    generatedCache: { edgesHash: "sha256:abc", edgesCount: 0 },
  };
  const out = serializeLockfile(lf);
  // [meta.toolchain] must appear after [meta], before any [[upstream.*]].
  const metaIdx = out.indexOf("[meta]\n");
  const toolchainIdx = out.indexOf("[meta.toolchain]\n");
  const cacheIdx = out.indexOf("[generated-cache]\n");
  assertEquals(metaIdx >= 0, true, "[meta] section missing");
  assertEquals(
    toolchainIdx > metaIdx,
    true,
    "[meta.toolchain] not after [meta]",
  );
  assertEquals(
    toolchainIdx < cacheIdx,
    true,
    "[meta.toolchain] not before [generated-cache]",
  );
  assertStringIncludes(out, `min-version = "0.6"`);
});

Deno.test("serializeLockfile: omits [meta.toolchain] when absent", () => {
  const lf: Lockfile = {
    schema: 1,
    meta: {
      markspecSchema: 1,
      lockedAt: "2026-05-27T12:00:00Z",
    },
    upstreams: [],
    boundEntries: [],
    edges: [],
    generatedCache: { edgesHash: "sha256:abc", edgesCount: 0 },
  };
  const out = serializeLockfile(lf);
  assertEquals(out.indexOf("[meta.toolchain]"), -1);
  assertEquals(out.indexOf("min-version"), -1);
});

Deno.test("lockfile round-trips with [meta.toolchain]", () => {
  const original: Lockfile = {
    schema: 1,
    meta: {
      markspecSchema: 1,
      lockedAt: "2026-05-27T12:00:00Z",
      toolchain: { minVersion: "0.6" },
    },
    upstreams: [],
    boundEntries: [],
    edges: [],
    generatedCache: { edgesHash: "sha256:abc", edgesCount: 0 },
  };
  const serialized = serializeLockfile(original);
  const { lockfile: parsed, diagnostics } = parseLockfile(serialized);
  assertEquals(diagnostics.length, 0);
  assertEquals(parsed, original);
});

Deno.test("lockfile round-trips without [meta.toolchain]", () => {
  const original: Lockfile = {
    schema: 1,
    meta: {
      markspecSchema: 1,
      lockedAt: "2026-05-27T12:00:00Z",
    },
    upstreams: [],
    boundEntries: [],
    edges: [],
    generatedCache: { edgesHash: "sha256:abc", edgesCount: 0 },
  };
  const serialized = serializeLockfile(original);
  const { lockfile: parsed, diagnostics } = parseLockfile(serialized);
  assertEquals(diagnostics.length, 0);
  assertEquals(parsed, original);
});

Deno.test("serializer: first line is the #:schema directive", () => {
  const toml = serializeLockfile(EMPTY_LOCKFILE);
  const firstLine = toml.split("\n")[0];
  assertEquals(
    firstLine,
    "#:schema https://driftsys.github.io/markspec/schemas/lock/v1.json",
  );
});

Deno.test("serializeLockfile: edge sort is total — colliding (source, relation, authored-target) differ only by targetUlid produce identical bytes regardless of input order", () => {
  // Two edges share (sourceUlid, relation, authoredTarget) but have different
  // targetUlids — a collision that the old comparator left as input-order-dependent.
  const edgeA = {
    sourceUlid: "01J0000000000000000000SRC1",
    relation: "Satisfies",
    authoredTarget: "SYS_DUP_0001",
    targetUlid: "01J0000000000000000000TGA1",
  };
  const edgeB = {
    sourceUlid: "01J0000000000000000000SRC1",
    relation: "Satisfies",
    authoredTarget: "SYS_DUP_0001",
    targetUlid: "01J0000000000000000000TGB2",
  };
  const base: Lockfile = {
    ...EMPTY_LOCKFILE,
    edges: [],
    generatedCache: { edgesHash: "sha256:x", edgesCount: 2 },
  };
  const toml1 = serializeLockfile({ ...base, edges: [edgeA, edgeB] });
  const toml2 = serializeLockfile({ ...base, edges: [edgeB, edgeA] });
  assertEquals(
    toml1,
    toml2,
    "both input permutations must produce identical bytes",
  );
});

Deno.test("serializeLockfile: emits [[edge]] tables sorted by (source, relation, authored-target)", () => {
  const lf: Lockfile = {
    schema: 1,
    meta: { markspecSchema: 1, lockedAt: "2026-06-06T00:00:00Z" },
    upstreams: [],
    boundEntries: [],
    edges: [
      {
        sourceUlid: "01J0000000000000000000SRC2",
        relation: "Satisfies",
        targetUlid: "01J0000000000000000000TGT2",
        authoredTarget: "SYS_BRK_0099",
      },
      {
        sourceUlid: "01J0000000000000000000SRC1",
        relation: "Satisfies",
        targetUlid: "01J0000000000000000000TGT1",
        authoredTarget: "SYS_BRK_0042",
      },
      {
        sourceUlid: "01J0000000000000000000SRC1",
        relation: "Derived-from",
        authoredTarget: "SYS_GONE_0001",
      },
    ],
    generatedCache: { edgesHash: "sha256:0", edgesCount: 0 },
  };
  const toml = serializeLockfile(lf);
  const firstSrc1 = toml.indexOf("01J0000000000000000000SRC1");
  const src2 = toml.indexOf("01J0000000000000000000SRC2");
  assertEquals(firstSrc1 < src2, true);
  assertStringIncludes(toml, "[[edge]]");
  assertStringIncludes(toml, 'relation        = "Satisfies"');
  assertStringIncludes(toml, 'authored-target = "SYS_BRK_0042"');
  const goneIdx = toml.indexOf('authored-target = "SYS_GONE_0001"');
  const goneBlock = toml.slice(goneIdx - 200, goneIdx);
  assertEquals(goneBlock.includes("01J0000000000000000000SRC1"), true);
  assertEquals(serializeLockfile(lf), toml); // determinism
});

Deno.test("serializeLockfile: edge order is total — colliding edges sort by target-ulid", () => {
  // Two edges that collide on (source-ulid, relation, authored-target) and
  // differ only in target-ulid. This arises when the same authored display ID
  // resolves to two different ULIDs (duplicate display IDs across files whose
  // first-wins tiebreak flips per machine). Without target-ulid in the
  // comparator, the stable sort preserves input order — which comes from an
  // unsorted Deno.readDir walk — so the bytes become machine-dependent.
  const edgeA: Lockfile["edges"][number] = {
    sourceUlid: "01J0000000000000000000SRC1",
    relation: "Satisfies",
    targetUlid: "01J0000000000000000000TGTA",
    authoredTarget: "SYS_DUP_0001",
  };
  const edgeB: Lockfile["edges"][number] = {
    sourceUlid: "01J0000000000000000000SRC1",
    relation: "Satisfies",
    targetUlid: "01J0000000000000000000TGTB",
    authoredTarget: "SYS_DUP_0001",
  };
  const base: Lockfile = {
    schema: 1,
    meta: { markspecSchema: 1, lockedAt: "2026-06-06T00:00:00Z" },
    upstreams: [],
    boundEntries: [],
    edges: [],
    generatedCache: { edgesHash: "sha256:0", edgesCount: 0 },
  };
  const forward = serializeLockfile({ ...base, edges: [edgeA, edgeB] });
  const reversed = serializeLockfile({ ...base, edges: [edgeB, edgeA] });
  assertEquals(forward, reversed); // permutation-independent → total order
});
