// packages/markspec/core/lock/serializer_test.ts
import { assertEquals, assertStringIncludes } from "@std/assert";
import { serializeLockfile } from "./serializer.ts";
import type { Lockfile } from "./model.ts";

const EMPTY_LOCKFILE: Lockfile = {
  schema: 1,
  meta: { markspecSchema: 1, lockedAt: "2026-05-25T12:00:00Z" },
  upstreams: [],
  boundEntries: [],
  generatedCache: { edgesHash: "sha256:e3b0c44", edgesCount: 0 },
};

Deno.test("serializeLockfile: empty lockfile produces deterministic TOML", () => {
  const toml = serializeLockfile(EMPTY_LOCKFILE);
  assertStringIncludes(toml, "# @generated by `markspec lock`");
  assertStringIncludes(toml, "schema = 1");
  assertStringIncludes(toml, "markspec-schema = 1");
  assertStringIncludes(toml, 'locked-at = "2026-05-25T12:00:00Z"');
  assertStringIncludes(toml, "[generated-cache]");
  assertStringIncludes(toml, 'edges-hash = "sha256:e3b0c44"');
  assertStringIncludes(toml, "edges-count = 0");
});

Deno.test("serializeLockfile: identical input produces byte-identical output", () => {
  const a = serializeLockfile(EMPTY_LOCKFILE);
  const b = serializeLockfile(EMPTY_LOCKFILE);
  assertEquals(a, b);
});

Deno.test("serializeLockfile: References sorted by slug", () => {
  const lf: Lockfile = {
    ...EMPTY_LOCKFILE,
    upstreams: [
      {
        kind: "reference",
        slug: "RFC-2119",
        id: "https://www.rfc-editor.org/rfc/rfc2119",
      },
      {
        kind: "reference",
        slug: "ISO-26262-6",
        id: "urn:iso:std:iso:26262:-6:ed-2",
      },
    ],
  };
  const toml = serializeLockfile(lf);
  const isoIdx = toml.indexOf("ISO-26262-6");
  const rfcIdx = toml.indexOf("RFC-2119");
  assertEquals(
    isoIdx < rfcIdx,
    true,
    "ISO must come before RFC alphabetically",
  );
});

Deno.test("serializeLockfile: bound-entry binding sub-table emission order", () => {
  const lf: Lockfile = {
    ...EMPTY_LOCKFILE,
    boundEntries: [{
      displayId: "REQ-107",
      ulid: "01HGW2Q8MNP3RSTVWXYZABCDEF",
      bindings: [
        {
          externalId: "jira:PROJ-1423",
          system: "jira",
          direction: "bidirectional",
          lockedAttributes: new Map([["Title", "sha256:abc"]]),
        },
        {
          externalId: "doors:/Project/Reqs/REQ-107",
          system: "doors",
          direction: "inbound",
          lockedAttributes: new Map([["Status", "sha256:def"]]),
        },
      ],
    }],
  };
  const toml = serializeLockfile(lf);
  // First binding (doors) must come fully (including its locked-attrs sub-table)
  // before the second binding (jira) — bindings are sorted by system name,
  // so doors < jira alphabetically.
  const doorsBindingIdx = toml.indexOf("doors:/Project");
  const doorsLockedIdx = toml.indexOf('Status = "sha256:def"');
  const jiraBindingIdx = toml.indexOf("jira:PROJ-1423");
  assertEquals(doorsBindingIdx < doorsLockedIdx, true);
  assertEquals(doorsLockedIdx < jiraBindingIdx, true);
});

Deno.test("serializeLockfile: TOML string escaping handles backslash, quote, and control chars", () => {
  const lf: Lockfile = {
    ...EMPTY_LOCKFILE,
    upstreams: [{
      kind: "reference",
      slug: "edge-case",
      // Backslash, double-quote, newline, carriage return, tab — all common
      // hazards in opaque external-system inputs.
      id: 'urn:test:back\\slash:quote"in:newline\nreturn\rtab\there',
    }],
  };
  const toml = serializeLockfile(lf);
  // Each metachar appears in its TOML-escaped form on the `id = "…"` line.
  assertStringIncludes(toml, "\\\\");
  assertStringIncludes(toml, '\\"');
  assertStringIncludes(toml, "\\n");
  assertStringIncludes(toml, "\\r");
  assertStringIncludes(toml, "\\t");
});
